para= int(input("Para miktanını giriniz: "))
yuz= int(para/100)
yuzk= int(para%100)
elli= int(yuzk/50)
ellik= int(yuzk%50)
yirmi= int(ellik/20)
yirmik= int(ellik%20)
on= int(yirmik/10)
print(yuz,"tane 100'lük\n"+str(elli),"tane 50'lik\n"+str(yirmi),"tane 20'lik\n"+str(on),"tane 10'luk banknotunuz vardır!\nToplam kullanılan baknot miktarı:",yuz+elli+yirmi+on)
